# Generated by Django 6.0 on 2026-03-21 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('management', 'Management Team'), ('tech', 'Tech Team'), ('pr', 'PR Team'), ('social_media', 'Social Media Team'), ('design', 'Designing Team'), ('core', 'Core Member Team')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description shown on the team page')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
            ],
            options={
                'verbose_name': 'Team Category',
                'verbose_name_plural': 'Team Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('photo', models.ImageField(blank=True, help_text='Square image recommended (300×300px+)', null=True, upload_to='team/photos/')),
                ('role', models.CharField(help_text='e.g. Team Lead, Frontend Dev', max_length=150)),
                ('bio', models.TextField(blank=True, help_text='Short bio (2–3 sentences)')),
                ('branch', models.CharField(blank=True, help_text='e.g. Computer Science', max_length=100)),
                ('year', models.CharField(blank=True, help_text='e.g. 2nd Year, Batch 2025', max_length=20)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True, help_text='Personal website or portfolio')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('leetcode', models.URLField(blank=True)),
                ('gfg_profile', models.URLField(blank=True, help_text='GeeksForGeeks profile URL')),
                ('skills', models.CharField(blank=True, help_text='Comma-separated e.g. Python, Django, React', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the page')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first within team')),
                ('joined_at', models.DateField(blank=True, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='app1.teamcategory')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['team__order', 'order', 'name'],
            },
        ),
    ]
