# Generated by Django 6.0 on 2026-03-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_teamcategory_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusMantri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, help_text='Square image recommended (400×400px+)', null=True, upload_to='campus_mantri/')),
                ('title', models.CharField(default='Campus Mantri', help_text='e.g. Campus Mantri, GFG Campus Ambassador', max_length=150)),
                ('tagline', models.CharField(blank=True, help_text='Short inspiring line shown below the name', max_length=220)),
                ('bio', models.TextField(blank=True, help_text='Full bio shown on the home page card')),
                ('branch', models.CharField(blank=True, max_length=100)),
                ('year', models.CharField(blank=True, max_length=30)),
                ('achievements', models.TextField(blank=True, help_text='One achievement per line. Shown as bullet points.')),
                ('github', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('gfg_profile', models.URLField(blank=True)),
                ('leetcode', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('portfolio', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
            ],
            options={
                'verbose_name': 'Campus Mantri',
                'verbose_name_plural': 'Campus Mantris',
                'ordering': ['order', 'name'],
            },
        ),
    ]
