# Generated by Django 6.0 on 2026-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_campusmantri'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.PositiveIntegerField(default=500)),
                ('events_hosted', models.PositiveIntegerField(default=40)),
                ('articles_published', models.PositiveIntegerField(default=100)),
                ('years_running', models.PositiveIntegerField(default=3)),
                ('active_teams', models.PositiveIntegerField(default=6)),
            ],
            options={
                'verbose_name': 'Site Statistics',
                'verbose_name_plural': 'Site Statistics',
            },
        ),
    ]
