# Generated by Django 6.0 on 2026-03-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_sitestats'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_tagline', models.CharField(default='About Us', help_text='Small label above the heading', max_length=120)),
                ('hero_heading', models.CharField(default='We Are GFG CGC Chapter', help_text='Main big heading', max_length=220)),
                ('hero_subtext', models.TextField(blank=True, help_text='Paragraph shown below the heading')),
                ('story_heading', models.CharField(default='Our Story', max_length=150)),
                ('story_body', models.TextField(blank=True, help_text='Multi-paragraph story. Use blank lines to separate paragraphs.')),
                ('vision_heading', models.CharField(default='Vision & Mission', max_length=150)),
                ('vision_text', models.TextField(blank=True, help_text='Vision statement')),
                ('mission_text', models.TextField(blank=True, help_text='Mission statement')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_address', models.TextField(blank=True, help_text='Full address shown on contact section')),
                ('contact_map_url', models.URLField(blank=True, help_text='Google Maps embed URL for contact section')),
                ('social_instagram', models.URLField(blank=True)),
                ('social_linkedin', models.URLField(blank=True)),
                ('social_twitter', models.URLField(blank=True)),
                ('social_github', models.URLField(blank=True)),
                ('social_youtube', models.URLField(blank=True)),
                ('social_discord', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(choices=[('🏆', '🏆 Trophy'), ('🥇', '🥇 Gold Medal'), ('🎖️', '🎖️ Medal'), ('⭐', '⭐ Star'), ('🚀', '🚀 Rocket'), ('💡', '💡 Bulb'), ('🌟', '🌟 Glowing Star'), ('🎯', '🎯 Target'), ('📢', '📢 Megaphone'), ('🤝', '🤝 Handshake'), ('💻', '💻 Laptop'), ('🌐', '🌐 Globe')], default='🏆', max_length=10)),
                ('date', models.DateField(blank=True, help_text='When this was achieved', null=True)),
                ('highlight', models.CharField(blank=True, help_text="Short bold stat e.g. '1st Place', '500+ attendees'", max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['order', '-date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ValueCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('⚡', '⚡ Lightning'), ('🤝', '🤝 Handshake'), ('💡', '💡 Bulb'), ('🌱', '🌱 Seedling'), ('🔥', '🔥 Fire'), ('🧠', '🧠 Brain'), ('🎯', '🎯 Target'), ('🌐', '🌐 Globe'), ('💎', '💎 Diamond'), ('🚀', '🚀 Rocket')], default='💡', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order'],
            },
        ),
    ]
