# Generated by Django 6.0 on 2026-03-21 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('blog_editor', 'Blog Editor'), ('event_manager', 'Event Manager'), ('team_manager', 'Team Manager'), ('moderator', 'Moderator')], default='blog_editor', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to revoke dashboard access')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='member_avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Role',
                'verbose_name_plural': 'Member Roles',
            },
        ),
    ]
